services:
  estagios-db:
    container_name: estagios-prod-db
    image: postgres:13
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/estagio_data
    volumes:
      - estagio_db_data:/var/lib/postgresql/estagio_data
    ports:
      - "50236:5432"
    networks:
      - fabrica-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 3

  estagios-web:
    container_name: estagios-prod-web
    build: .
    ports:
      - "5000:5000"
    depends_on:
      estagios-db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:5000 app:app --workers ${GUNICORN_WORKERS} --threads ${GUNICORN_THREADS} --timeout ${GUNICORN_TIMEOUT}"
    networks:
      - fabrica-network
    restart: always

volumes:
  estagio_db_data:


networks:
  fabrica-network:
    external: true
